### ISSUE TITLE
Refresh from template

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/ember-inspector#9]
This was delivered, then `ember-template` was updated. I normally don't like these "refresh from template" issues 'cause they should happen anyway, but this is more important because this lesson will be AT LEAST one template behind by the time 015 delivers this material.

**Comment by gaand** [comment]
This isn't actually based on the ember-template.  Perhaps it should be, but it's based on the super rental demo.

**Comment by gaand** [comment]
See #1

**Comment by payne-chris-r** [comment]
Should be closed
